"""update_category_and_product_model

Revision ID: 753717350a68
Revises: 0bc0d85b8517
Create Date: 2025-11-17 04:41:29.026854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '753717350a68'
down_revision: Union[str, None] = '0bc0d85b8517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'display_order')
    op.drop_column('categories', 'description')
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_url')
    op.add_column('categories', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
