"""add_link_id_to_complaint

Revision ID: 87a7758524c0
Revises: db0e187866db
Create Date: 2025-11-20 22:19:51.103107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87a7758524c0'
down_revision: Union[str, None] = 'db0e187866db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('link_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_complaints_link_id'), 'complaints', ['link_id'], unique=False)
    op.create_foreign_key(None, 'complaints', 'links', ['link_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_index(op.f('ix_complaints_link_id'), table_name='complaints')
    op.drop_column('complaints', 'link_id')
    # ### end Alembic commands ###
