"""add_chat_assignment_and_websocket_support

Revision ID: 9ea88006a995
Revises: 6e8068c46fa2
Create Date: 2025-11-17 05:37:53.447262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ea88006a995'
down_revision: Union[str, None] = '6e8068c46fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('assigned_sales_rep_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_links_assigned_sales_rep_id'), 'links', ['assigned_sales_rep_id'], unique=False)
    op.create_foreign_key(None, 'links', 'users', ['assigned_sales_rep_id'], ['id'])
    op.add_column('messages', sa.Column('sales_rep_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_messages_sales_rep_id'), 'messages', ['sales_rep_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'users', ['sales_rep_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_sales_rep_id'), table_name='messages')
    op.drop_column('messages', 'sales_rep_id')
    op.drop_constraint(None, 'links', type_='foreignkey')
    op.drop_index(op.f('ix_links_assigned_sales_rep_id'), table_name='links')
    op.drop_column('links', 'assigned_sales_rep_id')
    # ### end Alembic commands ###
